name: Atualizar Grafico de Linguagens

on:
  schedule:
    - cron: "0 0 * * *" # Roda sozinho todo dia à meia-noite
  workflow_dispatch: # Botão para você rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dá permissão para o robô salvar a imagem no seu repositório
    steps:
      - name: Gerar arquivo de linguagens
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" # Deixa vazio para focar apenas nas linguagens
          plugin_languages: yes
          plugin_languages_details: percentage
          output_action: commit
          committer_branch: languages-output # Cria a pasta/branch que você tentou usar
